media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view: 
      fields: [ title, date, categories ]
    fields:
      - name: layout
        type: string
        default: post
        hidden: true
      - name: date
        label: Date
        type: date
        options:
           time: true
           format: yyyy-MM-dd HH:mm
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: categories
        label: Categories
        type: string
  - name: pages
    label: Pages
    path: pages
    type: collection
    view: 
      fields: [ title, permalink ]
    fields:
      - name: body
        label: Body
        type: rich-text
      - name: layout
        type: string
        default: home
        hidden: true
      - name: title
        label: Title
        type: string
      - name: permalink
        lable: Permalink
        type: string
  - name: homepage
    label: Blog Homepage
    type: file
    path: index.md
  - name: config
    label: Jekyll config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)